# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1e7800620d690fe87b31b0563b81c3af4e478cd7c49f1ff1a586b6b45c75e569b13f227e8e9e4526a0b54fa79b7f4edb3750be7d26845628690c02a43e84cf5

test:
  secret_key_base: 3c5c6537b6ef642a3b080f053f93a1ed8c539487b9a9022ccef99345e32a87d27fec1b001b4de6fbfdc240186c9828aa1194394a84777d9134f99277ae507804

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
